### ISSUE TITLE
Download not working due to cross-origin requests

### ISSUE THREAD

**Issue by ggmendez** [Mendeley/mendeley-javascript-sdk#43]
I am trying to access the PDF files of my account from a visualization tool I am implementing. This is my download method associated to the files function of the JS API:

             download: requestFun('GET', '/files/{id}', ['id']

I am invoking the function like this: 
             var fileID = <file_ID>;
             MendeleySDK.API.files.download(fileID);

This is the error I get:

XMLHttpRequest cannot load https://api.mendeley.com/files/<file_ID>. The request was redirected to 'https://mendeley-files.s3.amazonaws.com/b4/...', which is disallowed for cross-origin requests that require preflight.

Any idea on how to solve this?

**Comment by paulwib** [comment]
Hi @ggmendez - unfortunately this is a restriction of the way browsers implement CORS combined with the current API. The API response includes a redirect header that the browser tries to follow, but then blocks because of CORS.

The way we work around this is to have a small piece of server-side code (called via Ajax) that will make the API request to `/files/{id}`, extract the `Location` header then return this in a JSON object. The client-side code can then do a redirect like `window.location = fileurl` to start the download.

We have discussed in the past having an endpoint that *doesn't* set a location header but instead puts the URL in the body of the response. I'll raise that again with our team, but in the meantime there is no way to do this with purely client-side code.
